<a href="https://colab.research.google.com/github/AnasAkenoun/Diamond_structure/blob/main/copy_of_lab_1_material_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define lattice vectors for diamond structure
a = 3.43 # lattice constant in Angstroms
lattice_vectors = np.array([[0.5*a, 0.5*a, 0], [0, 0.5*a, 0.5*a], [0.5*a, 0, 0.5*a]])

# Define basis vectors for diamond structure
basis_vectors = np.array([[0, 0, 0], [0.25*a, 0.25*a, 0.25*a]])

# Create a function to generate a diamond unit cell
def diamond_unit_cell():
    # Generate a list of atom positions in the unit cell
    atom_positions = []
    for i in range(3):
        for j in range(3):
            for k in range(3):
                for basis_vector in basis_vectors:
                    atom_position = i*lattice_vectors[0] + j*lattice_vectors[1] + k*lattice_vectors[2] + basis_vector
                    atom_positions.append(atom_position)
    return atom_positions

# Create three layers of the diamond structure
layer_1 = diamond_unit_cell()
layer_2 = [atom_position + lattice_vectors[2] for atom_position in layer_1]
layer_3 = [atom_position + 2*lattice_vectors[2] for atom_position in layer_1]

# Write positions of atoms in each layer to a .xyz file
with open('diamond.xyz', 'w') as f:
    # Write number of atoms in each layer
    f.write(f"{len(layer_1)}\n\n")

    # Write atom positions for layer 1
    for atom_position in layer_1:
        f.write(f"C {atom_position[0]} {atom_position[1]} {atom_position[2]}\n")

    # Write atom positions for layer 2
    for atom_position in layer_2:
        f.write(f"C {atom_position[0]} {atom_position[1]} {atom_position[2]}\n")

    # Write atom positions for layer 3
    for atom_position in layer_3:
        f.write(f"C {atom_position[0]} {atom_position[1]} {atom_position[2]}\n")

# Print the positions of atoms in each layer
print("Layer 1:")
for atom_position in layer_1:
    print(atom_position)

print("\nLayer 2:")
for atom_position in layer_2:
    print(atom_position)

print("\nLayer 3:")
for atom_position in layer_3:
    print(atom_position)

Layer 1:
[0. 0. 0.]
[0.8575 0.8575 0.8575]
[1.715 0.    1.715]
[2.5725 0.8575 2.5725]
[3.43 0.   3.43]
[4.2875 0.8575 4.2875]
[0.    1.715 1.715]
[0.8575 2.5725 2.5725]
[1.715 1.715 3.43 ]
[2.5725 2.5725 4.2875]
[3.43  1.715 5.145]
[4.2875 2.5725 6.0025]
[0.   3.43 3.43]
[0.8575 4.2875 4.2875]
[1.715 3.43  5.145]
[2.5725 4.2875 6.0025]
[3.43 3.43 6.86]
[4.2875 4.2875 7.7175]
[1.715 1.715 0.   ]
[2.5725 2.5725 0.8575]
[3.43  1.715 1.715]
[4.2875 2.5725 2.5725]
[5.145 1.715 3.43 ]
[6.0025 2.5725 4.2875]
[1.715 3.43  1.715]
[2.5725 4.2875 2.5725]
[3.43 3.43 3.43]
[4.2875 4.2875 4.2875]
[5.145 3.43  5.145]
[6.0025 4.2875 6.0025]
[1.715 5.145 3.43 ]
[2.5725 6.0025 4.2875]
[3.43  5.145 5.145]
[4.2875 6.0025 6.0025]
[5.145 5.145 6.86 ]
[6.0025 6.0025 7.7175]
[3.43 3.43 0.  ]
[4.2875 4.2875 0.8575]
[5.145 3.43  1.715]
[6.0025 4.2875 2.5725]
[6.86 3.43 3.43]
[7.7175 4.2875 4.2875]
[3.43  5.145 1.715]
[4.2875 6.0025 2.5725]
[5.145 5.145 3.43 ]
[6.0025 6.0025 4.2875]
[6.86  5.145 5.145]
[7.7175 6